console.log("This is loaded from the external JS");
var name = "Hiruy Dagnew";
var school = "CPCC";
let hobby = "Playing Soccer";
console.log(`Name: ${name}`);
console.log(`School: ${school}`);
console.log(`Hobby: ${hobby}`);
document.getElementById("name").innerHTML = "<b>Name: </b>"+name;
document.getElementById("school").innerHTML = "<b>School: </b>"+school;
document.getElementById("hobby").innerHTML = "<b>Hobby: </b>"+hobby;
